server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://www.ruokit.com:5432/oil_db
    username: postgres
    password: wngus123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  jackson:
    serialization:
      INDENT_OUTPUT: true
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

opinet:
  api:
    base-url: http://www.opinet.co.kr/api/aroundAll.do  # 오피넷 API 기본 URL

google:
  maps:
    api:
      base-url: https://maps.googleapis.com/maps/api/geocode/json

logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql: TRACE


